version: '2'
services:
  node:
    build:
      context: ..
      dockerfile: docker/node.docker
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    entrypoint: docker/entry-dev.sh
    volumes:
      - ../:/app
    environment:
      - NODE_PATH=/package/node_modules
      - DEBUG=true
  postgres:
    build:
      context: ..
      dockerfile: docker/postgres.docker
