FROM postgres:9.6

ENV POSTGRES_DB=riftforum_db
ENV POSTGRES_USER=riftforum_user
ENV POSTGRES_PASSWORD=riftforum_pass

RUN mkdir -p /docker-entrypoint-initdb.d
ADD docker/init.sql /docker-entrypoint-initdb.d
